### ISSUE TITLE
渲染过程细节

### ISSUE THREAD

**Issue by fyyjyx-github** [winterwindwang/Full-coverage-camouflage-adversarial-attack#1]
您好，我想请教下就是使用Neural Renderer将伪装图案渲染到3D车辆模型上时，是全覆盖了整个车辆模型的，但是现实条件是仅需要将图案覆盖在车辆的部分表面就行了，比如轮胎、车窗这些就不需要覆盖，那这个是怎么控制的呢？

**Comment by winterwindwang** [comment]
通过faces.txt文件控制优化的纹理区域。具体操作是在3DMax软件里手动选择要优化的face。

**Comment by fyyjyx-github** [comment]
好的，我再看看，也就是还需要对masks文件夹下的每个mask使用3DMax软件进行处理是吗。
那使用YOLOv3训练纹理的命令具体是怎样的呢，那个用于训练的文件是src下的train_camouflage_yolov3吗

**Comment by winterwindwang** [comment]
不需要对mask文件下的文件处理，只需要修改carassets文件夹下的exterior_face.txt就行。要训练起来，还需要配置数据文件。

**Comment by fyyjyx-github** [comment]
好的，那您有保存下来的论文中的training set数据集吗，就是真实车辆模型在Carla模拟器中的街景中的图片。

![image](https://user-images.githubusercontent.com/76107632/147716414-e94dec7f-642f-4b64-89b6-95fd28f37289.png)

**Comment by winterwindwang** [comment]
链接：https://pan.baidu.com/s/1A-LTCfo7P6PjRPkpBm2LMg 
提取码：tm3m
你把这里提供的label放在carassets/train_label里面。数据集在DAS(https://github.com/nlsde-safety-team/DualAttentionAttack)里面下载，数据集太大我这就不提供了。

**Comment by fyyjyx-github** [comment]
最后生成的camouflage要怎么可视化出来呢，就是单看这个camouflage的话。

**Comment by winterwindwang** [comment]
迷彩是没法单独看的，必须渲染在车上才能看，我记得repo里有相关的代码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月31日(周五) 中午11:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] 渲染过程细节 (Issue #1)




 
最后生成的camouflage要怎么可视化出来呢，就是单看这个camouflage的话。

**Comment by fyyjyx-github** [comment]
好的。还有就是这个data/carla.yaml、data/hyp.scratch.yaml文件没有在文件夹中找到，是要在哪里获得呢？因为在运行时需要提供这2个文件的路径作为参数。

**Comment by winterwindwang** [comment]
不好意思，上传文件的时候，把data文件夹设置成.gitignore了。现在你可以去看看了，如果需要可以把你的微信发给我

**Comment by fyyjyx-github** [comment]
好的，xin640179
