### ISSUE TITLE
I would like to ask the author, is neuralRender installed in the same way as DAS? Thank you!

### ISSUE THREAD

**Issue by logicsh** [winterwindwang/Full-coverage-camouflage-adversarial-attack#12]
I would like to ask the author, is neuralRender installed in the same way as DAS? Thank you!

**Comment by winterwindwang** [comment]
The neural renderer I was used is based on [https://github.com/daniilidis-group/neural_renderer](https://github.com/daniilidis-group/neural_renderer),  but I was modify it for FCA, the modified version is here [https://github.com/winterwindwang/neural_renderer](https://github.com/winterwindwang/neural_renderer)

**Comment by logicsh** [comment]
ok，thanks！
