### ISSUE TITLE
Do chainer and other packages have version installation requirements? or it's better to follow das？

### ISSUE THREAD

**Issue by logicsh** [winterwindwang/Full-coverage-camouflage-adversarial-attack#14]
Do chainer and other packages have version installation requirements? or it's better to follow das？

**Comment by winterwindwang** [comment]
I suggest to use the pytorch version. In the Readme file, i provide a modifidd version of neural renderer.



---Original---
From: ***@***.***&gt;
Date: Mon, May 2, 2022 21:19 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [winterwindwang/Full-coverage-camouflage-adversarial-attack] Do chainer and other packages have version installation requirements? or it's better to follow das？ (Issue #14)




 
Do chainer and other packages have version installation requirements? or it's better to follow das？

**Comment by logicsh** [comment]
ok,thanks
