### ISSUE TITLE
The resulting texture is very shallow

### ISSUE THREAD

**Issue by logicsh** [winterwindwang/Full-coverage-camouflage-adversarial-attack#15]
The program works, but the texture generated after 100 rounds of training is very shallow, which is different from the sample texture given in the project, with basically no color but a little disturbance. May I ask whether the author has ever encountered such a situation in the training process

**Comment by winterwindwang** [comment]
Could you provide the rendered image?

**Comment by logicsh** [comment]
![Uploading test_total99.png…]()
This is a picture of the vehicle after applying the textures I got from 100 rounds of training

**Comment by winterwindwang** [comment]
> 

The image was not success uploaded. I am confused about the 100 rounds of training, do you mean 100 rounds of 1 epoch? If so, try to complete the training.

**Comment by logicsh** [comment]
sorry，it is not the 100 rounds.It is 100 epochs. 
![test_total4](https://user-images.githubusercontent.com/83349759/166647222-d073d92d-cbaf-42a1-bd09-378cb6bd56f3.png)

**Comment by winterwindwang** [comment]
In my experiment, I run 5-10 epochs. Please check the renderer image in the early stage (e.g., 5-th epoch) of training. In addition, ensure to use of the entire training image.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月4日(星期三) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] The resulting texture is very shallow (Issue #15)





 
sorry，it is not the 100 rounds.It is 100 epochs.

**Comment by logicsh** [comment]
Thanks!I will check the data set, preliminary analysis is that there is a problem with the label.

**Comment by logicsh** [comment]
When creating a cache file for the first time, it seems that too many images are ignored because of the tag (before 10000 images are mostly ignored). The TAB is downloaded from github's question answer baidu web disk link.
![e36bac30f8f9f929f5e67faa204359a](https://user-images.githubusercontent.com/83349759/166652804-edb61acc-53d5-44a0-bf2d-543505d331f7.png)

**Comment by logicsh** [comment]
I seem to have found the reason, thank you very much!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by winterwindwang** [comment]
Good job!



---Original---
From: ***@***.***&gt;
Date: Wed, May 4, 2022 18:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] The resulting texture is very shallow (Issue #15)




 
I seem to have found the reason, thank you very much!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Francisapzii** [comment]
> The program works, but the texture generated after 100 rounds of training is very shallow, which is different from the sample texture given in the project, with basically no color but a little disturbance. May I ask whether the author has ever encountered such a situation in the training process

Could you please explain how you get these code work?

**Comment by qwc0121** [comment]
> 我好像找到了原因，非常感谢!!!!!!!!!!!!!!!!!!!!!!!!

请问你最终得到了和原作者提供的纹理效果类似的纹理吗，我翻阅了你所有的提问，发现我遇到的问题和你基本一致，虽然解决了，但是得到的纹理在进行测试时效果比较差
