### ISSUE TITLE
How can I get the obj file after attaching the texture

### ISSUE THREAD

**Issue by logicsh** [winterwindwang/Full-coverage-camouflage-adversarial-attack#17]
I would like to know if the obJ file after attaching the texture can be obtained, because I saw the animation on github display page. And  thanks to the author for answering the question before, I have successfully run the code and have a preliminary effect .

**Comment by zhoujiawei2** [comment]
请问如何做到呢？

**Comment by winterwindwang** [comment]
> 

针对该问题，暂时没有很好的办法，因为优化的纹理没法转换成PNG格式。物理实验的步骤是：渲染不同角度涂装迷彩的图片，然后把纹理裁剪下来，贴到toy car上。要做真车实验，需要专业建模人员的帮助。
