### ISSUE TITLE
train_new

### ISSUE THREAD

**Issue by zytxxn** [winterwindwang/Full-coverage-camouflage-adversarial-attack#2]
请问train_new是怎么得到的

**Comment by winterwindwang** [comment]
把DAS数据中的图片提取保存下来



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 17, 2022 21:30 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [winterwindwang/Full-coverage-camouflage-adversarial-attack] train_new (Issue #2)




 
请问train_new是怎么得到的

**Comment by zytxxn** [comment]
DAS数据是npz格式的，我是需要额外再用代码提取出来吗？保存格式是.npy还是.jpg?

**Comment by winterwindwang** [comment]
提出来保存成.png。其实这一步不是必须的，真正训练的时候并没有用到这些图片，用的.npz里面的图片。因为yolov3加载数据时，利用图片名字来找对应的标注，所以为了方便我们就把图片保存在一个单独的文件夹。你可以尝试建一个train_new文件夹，然后把mask图片12500张复制到里面。



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 17, 2022 21:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] train_new (Issue #2)




 
DAS数据是npz格式的，我是需要额外再用代码提取出来吗？保存格式是.npy还是.jpg?
