### ISSUE TITLE
total_img errors occur like this

### ISSUE THREAD

**Issue by logicsh** [winterwindwang/Full-coverage-camouflage-adversarial-attack#20]
I would like to ask why most total_img errors occur like this during training, so the detection loss is also wrong

 
![test_total_1_14](https://user-images.githubusercontent.com/83349759/176337570-0ad0d5cc-0ef1-415f-9a99-45de7d832cce.png)

**Comment by logicsh** [comment]
ok，it is solved.

**Comment by Luochangjiang10** [comment]
could you tell me how to solve it？ I have the same problem，thank you
