### ISSUE TITLE
在运行神经渲染器的save_obj中，遇到cuda问题

### ISSUE THREAD

**Issue by logicsh** [winterwindwang/Full-coverage-camouflage-adversarial-attack#21]
File "/root/Full-coverage-camouflage-adversarial-attack-gh-pages-gengxinde/src/shiyan_save_obj.py", line 48, in create_texture_image
    image = image.cpu()
RuntimeError: CUDA error: an illegal memory access was encountered
请问作者能成功运行save_obj.py吗

**Comment by winterwindwang** [comment]
save_obj函数无法保存准确的纹理。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月3日(周日) 晚上6:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [winterwindwang/Full-coverage-camouflage-adversarial-attack] 在运行神经渲染器的save_obj中，遇到cuda问题 (Issue #21)




 
File "/root/Full-coverage-camouflage-adversarial-attack-gh-pages-gengxinde/src/shiyan_save_obj.py", line 48, in create_texture_image
 image = image.cpu()
 RuntimeError: CUDA error: an illegal memory access was encountered
 请问作者能成功运行save_obj.py吗

**Comment by logicsh** [comment]
好嘞，那请问作者是如何得到主页的旋转动画检测效果的呢，我以为是得到了应用伪装纹理的obj来着，谢谢作者回复~

**Comment by logicsh** [comment]
好嘞，那请问作者这个可以得到应用伪装纹理后的obj文件或者纹理的图片格式文件不，好应用到物理域看效果，谢谢作者回复~

**Comment by winterwindwang** [comment]
参考neural_renderer的example.py



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月3日(周日) 晚上8:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] 在运行神经渲染器的save_obj中，遇到cuda问题 (Issue #21)




 
好嘞，那请问作者是如何得到主页的旋转动画检测效果的呢，我以为是得到了应用伪装纹理的obj来着，谢谢作者回复~

**Comment by Francisapzii** [comment]
> File "/root/Full-coverage-camouflage-adversarial-attack-gh-pages-gengxinde/src/shiyan_save_obj.py", line 48, in create_texture_image image = image.cpu() RuntimeError: CUDA error: an illegal memory access was encountered 请问作者能成功运行save_obj.py吗

请问找到texture变image的方法了吗？具体如何做？
