### ISSUE TITLE
May I ask if the author has successfully printed the texture picture? Thank you for your reply！

### ISSUE THREAD

**Issue by logicsh** [winterwindwang/Full-coverage-camouflage-adversarial-attack#23]
May I ask if the author has successfully printed the texture picture? Thank you for your reply！

**Comment by winterwindwang** [comment]
We adopt a manner similar to DAS to print the adversarial texture. Please see the paper for details.

**Comment by logicsh** [comment]
Thanks!Do you have this problem :RuntimeRrror: CUDA error: operation not supported on global/shared address during printing the texture?
