### ISSUE TITLE
I would like to ask the author whether the training interface is consistent with your training at that time. Because the loss is still oscillating in the later rounds, and the grad mean of the texture has always been 0, I am a little worried about my training   

### ISSUE THREAD

**Issue by logicsh** [winterwindwang/Full-coverage-camouflage-adversarial-attack#26]
I would like to ask the author whether the training interface is consistent with your training at that time. Because the loss is still oscillating in the later rounds, and the grad mean of the texture has always been 0, I am a little worried about my training
![f3d3f30de494595243e50896b558e6a](https://user-images.githubusercontent.com/83349759/180606216-fbcf91c7-8f44-4ba9-b097-7953ffe0df29.png)

**Comment by logicsh** [comment]
I changed the load file section slightly to print the loaded file path each time it is loaded. Thank you for your answer!

**Comment by AutumnYQ** [comment]
have you solved it? may i ask how? my cls loss is always 0 , as well as grad.

**Comment by winterwindwang** [comment]
> have you solved it? may i ask how? my cls loss is always 0 , as well as grad.

It will not influence the result.  Waiting for the training to be completed and to check the intermediate rendered image.

**Comment by AutumnYQ** [comment]
> > have you solved it? may i ask how? my cls loss is always 0 , as well as grad.
> 
> It will not influence the result. Waiting for the training to be completed and to check the intermediate rendered image.


Got it! thank u!

**Comment by qwc0121** [comment]
> > > 你解决了吗？请问怎么做到的？我的 CLS 损失始终为 0 ，以及 grad。
> > 
> > 
> > 它不会影响结果。等待训练完成并检查中间渲染的图像。
> 
> 明白了！谢谢！

请问你最终复现的纹理效果和原作者提供的类似吗，我复现的纹理比作者提供的效果差很多
