### ISSUE TITLE
The ground truth?

### ISSUE THREAD

**Issue by mamougo** [winterwindwang/Full-coverage-camouflage-adversarial-attack#28]

**Comment by mamougo** [comment]
I am wondering how did you get the ground truth corresponding to the DAS dataset?

**Comment by winterwindwang** [comment]
> I am wondering how did you get the ground truth corresponding to the DAS dataset?

Please refer to 'src/carla_dataset/readme.md'

**Comment by mamougo** [comment]
> Please refer to 'src/carla_dataset/readme.md'

> 

Thanks a lot!
