### ISSUE TITLE
pytorch

### ISSUE THREAD

**Issue by zytxxn** [winterwindwang/Full-coverage-camouflage-adversarial-attack#3]
请问安装的pytorch是什么版本的呀

**Comment by zytxxn** [comment]
训练train_camouflage_yolov3.py的时候出现了以下错误，能指点一下吗？真的十分感谢！
“
train: Scanning 'data\phy_attack\train_label_new.cache' images and labels... 12500 found, 3000 missing, 0 empty, 0 corrupted: 100%|██████████| 15500/15500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "F:/torch/Full-coverage-camouflage-adversarial-attack-gh-pages/src/train_camouflage_yolov3.py", line 359, in <module>
    train(hyp, opt, device)
  File "F:/torch/Full-coverage-camouflage-adversarial-attack-gh-pages/src/train_camouflage_yolov3.py", line 167, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, faces, texture_size, vertices, opt,
  File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\datasets_fca.py", line 64, in create_dataloader
    dataset = LoadImagesAndLabels(path, faces, texture_size, vertices,imgsz, batch_size,
  File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\datasets_fca.py", line 245, in __init__
    self.np.device = faces.device
AttributeError: 'numpy.ndarray' object has no attribute 'device'
”

**Comment by winterwindwang** [comment]
> datasets_fca

你好，PyTorch的版本是1.8.0。对于你这个错误，你查看一下读出的3D模型是否在cuda中，我这边的设备是在cuda里面的，所以我直接用face.device。如果不在的话，你可以在读取3D模型后（在train_camouflage_yolov3.py），手动将读取的模型放到cuda中。在train_camouflage_yolov3.py中，使用类似faces = faces.to(device)的代码。还有，最新的数据标签在https://pan.baidu.com/s/18ZcQQgsr1DFbyUK4YVQ8WQ 提取码 idrl

**Comment by zytxxn** [comment]
请问cuda的版本是多少？10.2吗？

**Comment by winterwindwang** [comment]
11.0



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 18, 2022 01:11 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] pytorch (Issue #3)




 
请问cuda的版本是多少？10.2吗？

**Comment by zytxxn** [comment]
你好，训练失败貌似没有读取出3D模型，只有train_label_new.cache。

**Comment by winterwindwang** [comment]
> 你好，训练失败貌似没有读取出3D模型，只有train_label_new.cache。

你用的neural renderer是哪个版本？报了什么错。

**Comment by zytxxn** [comment]
我用的neural-renderer-pytorch 1.1.3。
按您之前说的改了之后，现在报的错是这个：
D:\Anaconda\envs\pytorch\python.exe F:/torch/Full-coverage-camouflage-adversarial-attack-gh-pages/src/train_camouflage_yolov3.py
logs/epoch-10+batch_size-1+lr-0.01+model-resnet50+loss_func-loss_midu+loss_content+loss_smooth+lamb-0.0001+D1-0.9+D2-0.1+T-0.0001+
github: skipping check (not a git repository)
YOLOv3  2022-1-5 torch 1.7.1+cu110 CUDA:0 (GeForce 940MX, 2048.0MB)

Namespace(agnostic_nms=False, batch_size=1, bbox_interval=-1, cache_images=False, cfg='', classes=[2], conf_thres=0.25, d1=0.9, d2=0.1, data='data/carla.yaml', datapath='F:/PythonPro/DualAttentionAttack/data/', device='', epochs=10, evolve=False, exist_ok=False, faces='carassets/exterior_face.txt', global_rank=-1, hyp='data/hyp.scratch.yaml', img_size=[640, 640], iou_thres=0.45, lamb=0.0001, lr=0.01, max_det=1000, name='exp', noautoanchor=False, nosave=False, notest=False, obj_file='carassets/audi_et_te.obj', project='runs/train', resume=False, save_dir='runs\\train\\exp31', save_period=-1, single_cls=False, t=0.0001, total_batch_size=1, weights='yolov3.pt', workers=8, world_size=1)
tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0
wandb: Install Weights & Biases for YOLOv3 logging with 'pip install wandb' (recommended)

                 from  n    params  module                                  arguments                     
  0                -1  1       928  models.common.Conv                      [3, 32, 3, 1]                 
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     20672  models.common.Bottleneck                [64, 64]                      
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    164608  models.common.Bottleneck                [128, 128]                    
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  8   2627584  models.common.Bottleneck                [256, 256]                    
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  8  10498048  models.common.Bottleneck                [512, 512]                    
  9                -1  1   4720640  models.common.Conv                      [512, 1024, 3, 2]             
 10                -1  4  20983808  models.common.Bottleneck                [1024, 1024]                  
 11                -1  1   5245952  models.common.Bottleneck                [1024, 1024, False]           
 12                -1  1    525312  models.common.Conv                      [1024, 512, [1, 1]]           
 13                -1  1   4720640  models.common.Conv                      [512, 1024, 3, 1]             
 14                -1  1    525312  models.common.Conv                      [1024, 512, 1, 1]             
 15                -1  1   4720640  models.common.Conv                      [512, 1024, 3, 1]             
 16                -2  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 17                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 18           [-1, 8]  1         0  models.common.Concat                    [1]                           
 19                -1  1   1377792  models.common.Bottleneck                [768, 512, False]             
 20                -1  1   1312256  models.common.Bottleneck                [512, 512, False]             
 21                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 22                -1  1   1180672  models.common.Conv                      [256, 512, 3, 1]              
 23                -2  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 24                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 25           [-1, 6]  1         0  models.common.Concat                    [1]                           
 26                -1  1    344832  models.common.Bottleneck                [384, 256, False]             
 27                -1  2    656896  models.common.Bottleneck                [256, 256, False]             
 28      [27, 22, 15]  1    457725  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [256, 512, 1024]]
Model Summary: 333 layers, 61949149 parameters, 61949149 gradients

Transferred 440/440 items from yolov3.pt
Scaled weight_decay = 0.0005
train: Scanning 'data\phy_attack\train_label_new.cache' images and labels... 12500 found, 3000 missing, 0 empty, 0 corrupted: 100%|██████████| 15500/15500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "F:/torch/Full-coverage-camouflage-adversarial-attack-gh-pages/src/train_camouflage_yolov3.py", line 359, in <module>
    train(hyp, opt, device)
  File "F:/torch/Full-coverage-camouflage-adversarial-attack-gh-pages/src/train_camouflage_yolov3.py", line 167, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, faces, texture_size, vertices, opt,
  File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\datasets_fca.py", line 64, in create_dataloader
    dataset = LoadImagesAndLabels(path, faces, texture_size, vertices,imgsz, batch_size,
  File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\datasets_fca.py", line 252, in __init__
    self.mask_renderer = nmr.NeuralRenderer(img_size=img_size).to(self.device)
  File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\nmr_test.py", line 204, in __init__
    self.renderer = NMR()
  File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\nmr_test.py", line 77, in __init__
    renderer = neural_renderer.Renderer(camera_mode='look')
TypeError: __init__() got an unexpected keyword argument 'camera_mode'

**Comment by winterwindwang** [comment]
> 我用的neural-renderer-pytorch 1.1.3。 按您之前说的改了之后，现在报的错是这个： D:\Anaconda\envs\pytorch\python.exe F:/torch/Full-coverage-camouflage-adversarial-attack-gh-pages/src/train_camouflage_yolov3.py logs/epoch-10+batch_size-1+lr-0.01+model-resnet50+loss_func-loss_midu+loss_content+loss_smooth+lamb-0.0001+D1-0.9+D2-0.1+T-0.0001+ github: skipping check (not a git repository) YOLOv3 2022-1-5 torch 1.7.1+cu110 CUDA:0 (GeForce 940MX, 2048.0MB)
> 
> Namespace(agnostic_nms=False, batch_size=1, bbox_interval=-1, cache_images=False, cfg='', classes=[2], conf_thres=0.25, d1=0.9, d2=0.1, data='data/carla.yaml', datapath='F:/PythonPro/DualAttentionAttack/data/', device='', epochs=10, evolve=False, exist_ok=False, faces='carassets/exterior_face.txt', global_rank=-1, hyp='data/hyp.scratch.yaml', img_size=[640, 640], iou_thres=0.45, lamb=0.0001, lr=0.01, max_det=1000, name='exp', noautoanchor=False, nosave=False, notest=False, obj_file='carassets/audi_et_te.obj', project='runs/train', resume=False, save_dir='runs\train\exp31', save_period=-1, single_cls=False, t=0.0001, total_batch_size=1, weights='yolov3.pt', workers=8, world_size=1) tensorboard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/ hyperparameters: lr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0 wandb: Install Weights & Biases for YOLOv3 logging with 'pip install wandb' (recommended)
> 
> ```
>              from  n    params  module                                  arguments                     
> ```
> 
> 0 -1 1 928 models.common.Conv [3, 32, 3, 1] 1 -1 1 18560 models.common.Conv [32, 64, 3, 2] 2 -1 1 20672 models.common.Bottleneck [64, 64] 3 -1 1 73984 models.common.Conv [64, 128, 3, 2] 4 -1 2 164608 models.common.Bottleneck [128, 128] 5 -1 1 295424 models.common.Conv [128, 256, 3, 2] 6 -1 8 2627584 models.common.Bottleneck [256, 256] 7 -1 1 1180672 models.common.Conv [256, 512, 3, 2] 8 -1 8 10498048 models.common.Bottleneck [512, 512] 9 -1 1 4720640 models.common.Conv [512, 1024, 3, 2] 10 -1 4 20983808 models.common.Bottleneck [1024, 1024] 11 -1 1 5245952 models.common.Bottleneck [1024, 1024, False] 12 -1 1 525312 models.common.Conv [1024, 512, [1, 1]] 13 -1 1 4720640 models.common.Conv [512, 1024, 3, 1] 14 -1 1 525312 models.common.Conv [1024, 512, 1, 1] 15 -1 1 4720640 models.common.Conv [512, 1024, 3, 1] 16 -2 1 131584 models.common.Conv [512, 256, 1, 1] 17 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest'] 18 [-1, 8] 1 0 models.common.Concat [1] 19 -1 1 1377792 models.common.Bottleneck [768, 512, False] 20 -1 1 1312256 models.common.Bottleneck [512, 512, False] 21 -1 1 131584 models.common.Conv [512, 256, 1, 1] 22 -1 1 1180672 models.common.Conv [256, 512, 3, 1] 23 -2 1 33024 models.common.Conv [256, 128, 1, 1] 24 -1 1 0 torch.nn.modules.upsampling.Upsample [None, 2, 'nearest'] 25 [-1, 6] 1 0 models.common.Concat [1] 26 -1 1 344832 models.common.Bottleneck [384, 256, False] 27 -1 2 656896 models.common.Bottleneck [256, 256, False] 28 [27, 22, 15] 1 457725 models.yolo.Detect [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [256, 512, 1024]] Model Summary: 333 layers, 61949149 parameters, 61949149 gradients
> 
> Transferred 440/440 items from yolov3.pt Scaled weight_decay = 0.0005 train: Scanning 'data\phy_attack\train_label_new.cache' images and labels... 12500 found, 3000 missing, 0 empty, 0 corrupted: 100%|██████████| 15500/15500 [00:00<?, ?it/s] Traceback (most recent call last): File "F:/torch/Full-coverage-camouflage-adversarial-attack-gh-pages/src/train_camouflage_yolov3.py", line 359, in train(hyp, opt, device) File "F:/torch/Full-coverage-camouflage-adversarial-attack-gh-pages/src/train_camouflage_yolov3.py", line 167, in train dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, faces, texture_size, vertices, opt, File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\datasets_fca.py", line 64, in create_dataloader dataset = LoadImagesAndLabels(path, faces, texture_size, vertices,imgsz, batch_size, File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\datasets_fca.py", line 252, in **init** self.mask_renderer = nmr.NeuralRenderer(img_size=img_size).to(self.device) File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\nmr_test.py", line 204, in **init** self.renderer = NMR() File "F:\torch\Full-coverage-camouflage-adversarial-attack-gh-pages\src\utils\nmr_test.py", line 77, in **init** renderer = neural_renderer.Renderer(camera_mode='look') TypeError: **init**() got an unexpected keyword argument 'camera_mode'

你先弄明白nueral renderer怎么用吧

**Comment by zytxxn** [comment]
作者你好！请问train_new和DAS所提供的masks是一样的吗？

**Comment by zytxxn** [comment]
请问训练出来之后如何测试呢？

**Comment by winterwindwang** [comment]
> 作者你好！请问train_new和DAS所提供的masks是一样的吗？

与训练方式类似，加载训练好的纹理文件，然后在测试集上得到渲染图片（对抗样本），最后进行测试。

**Comment by sctalish** [comment]
大佬 和src在同目录下的nerual_renderer目录下，如果要在py文件中调用cpp文件是不是要运行nerual_renderer下的setup.py呀？救救孩子叭.....

**Comment by winterwindwang** [comment]
> 大佬 和src在同目录下的nerual_renderer目录下，如果要在py文件中调用cpp文件是不是要运行nerual_renderer下的setup.py呀？救救孩子叭.....

在不同的目录下安装nerual_renderer与FCA，以避免不必要的问题

**Comment by sctalish** [comment]
好嘞 孩子还有个小问题。就是我现在想跑下nerual_renderer下examples的example1.py，但一直提示load_obj有问题，打开load_obj.py又提示import neural_renderer.neural_renderer.cuda.load_textures_cuda as load_textures_cuda有问题，就又打开了cuda下的load_textures_cuda.cpp，但该文件是正常的。就想着应该是py文件中调用cpp文件所写的函数导致的错误。百度了好半天没能解决，应该咋搞这个呀？

**Comment by winterwindwang** [comment]
neural_renderer安装请参考“https://winterwindwang.github.io/2021/07/22/nerual_rendered_build.html”&nbsp;


王冬华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月24日(星期四) 下午2:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] pytorch (Issue #3)





 
好嘞 孩子还有个小问题。就是我现在想跑下nerual_renderer下examples的example1.py，但一直提示load_obj有问题，打开load_obj.py又提示import neural_renderer.neural_renderer.cuda.load_textures_cuda as load_textures_cuda有问题，就又打开了cuda下的load_textures_cuda.cpp，但该文件是正常的。就想着应该是py文件中调用cpp文件所写的函数导致的错误。百度了好半天没能解决，应该咋搞这个呀？

**Comment by sctalish** [comment]
收到



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月24日 14:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] pytorch (Issue #3) |

neural_renderer安装请参考“https://winterwindwang.github.io/2021/07/22/nerual_rendered_build.html”&nbsp;


王冬华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;;
发送时间: 2022年11月24日(星期四) 下午2:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;; "State ***@***.***&gt;;
主题: Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] pytorch (Issue #3)






好嘞 孩子还有个小问题。就是我现在想跑下nerual_renderer下examples的example1.py，但一直提示load_obj有问题，打开load_obj.py又提示import neural_renderer.neural_renderer.cuda.load_textures_cuda as load_textures_cuda有问题，就又打开了cuda下的load_textures_cuda.cpp，但该文件是正常的。就想着应该是py文件中调用cpp文件所写的函数导致的错误。百度了好半天没能解决，应该咋搞这个呀？
