### ISSUE TITLE
有关相机位置和角度的问题

### ISSUE THREAD

**Issue by lzclzclzc12** [winterwindwang/Full-coverage-camouflage-adversarial-attack#31]
运行了一下train_new中的图片，但是生成出来的图片是这样的：
![11](https://user-images.githubusercontent.com/44523868/220300709-0df9f214-e0ba-46b4-bd6a-8534985a59f1.jpg)
![12](https://user-images.githubusercontent.com/44523868/220300669-d74bae99-18e6-43aa-bc57-36a7ad707124.jpg)
是不是这个函数写的有点问题呢
<img width="896" alt="image" src="https://user-images.githubusercontent.com/44523868/220300938-4c74b0ae-6c17-4e85-b68c-be63d89888d4.png">
我想问一下这个函数里cam_direct和cam_up的含义是什么

**Comment by winterwindwang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好，安装readme中提到的nerual_renderer应该可以解决这个问题，我对这部分进行了修改。
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年2月21日 17:15
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [winterwindwang/Full-coverage-camouflage-adversarial-attack] 有关相机位置和角度的问题 (Issue #31)
        
      
    
  
  

运行了一下train_new中的图片，但是生成出来的图片是这样的：





是不是这个函数写的有点问题呢



我想问一下这个函数里cam_direct和cam_up的含义是什么

**Comment by lzclzclzc12** [comment]
> 

感谢您的回复！我重新装了您 https://github.com/winterwindwang/neural_renderer/tree/master/neural_renderer 中的neural_renderer版本，但是好像问题还是没有解决，生成的图片：
<img width="643" alt="1676982094813" src="https://user-images.githubusercontent.com/44523868/220343781-9aeff36e-22dd-423b-b684-dba510dcbe68.png">
我确保用的是修改后的neural_renderer
<img width="895" alt="1676982195068" src="https://user-images.githubusercontent.com/44523868/220344133-47704067-52ff-4cd3-94b2-f52b2961d88b.png">

**Comment by winterwindwang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    看看look_up.py文件
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年2月21日 20:24
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] 有关相机位置和角度的问题 (Issue #31)
        
      
    
  
  





感谢您的回复！我重新装了您中的neural_renderer版本，但是好像问题还是没有解决，生成的图片：



我确保用的是修改后的neural_renderer

**Comment by lzclzclzc12** [comment]
> 

感谢您的耐心回复！成功了！我的nr.look_at函数的参数没改。

**Comment by Francisapzii** [comment]
> 运行了一下train_new中的图片，但是生成出来的图片是这样的： ![11](https://user-images.githubusercontent.com/44523868/220300709-0df9f214-e0ba-46b4-bd6a-8534985a59f1.jpg) ![12](https://user-images.githubusercontent.com/44523868/220300669-d74bae99-18e6-43aa-bc57-36a7ad707124.jpg) 是不是这个函数写的有点问题呢 <img alt="image" width="896" src="https://user-images.githubusercontent.com/44523868/220300938-4c74b0ae-6c17-4e85-b68c-be63d89888d4.png"> 我想问一下这个函数里cam_direct和cam_up的含义是什么

请问一下，这个是怎么生成出来的？
