### ISSUE TITLE
渲染过后的图片小于mask的大小

### ISSUE THREAD

**Issue by zhoujiawei2** [winterwindwang/Full-coverage-camouflage-adversarial-attack#33]
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/1995fd5f-bd22-4794-8625-4db3eeb1738a)
并且训练十个epoch的训练效果很不好，请问是否是这个原因影响，这个问题该怎么解决呢？使用的是您更改的neural_renderer

**Comment by winterwindwang** [comment]
你是怎么测试的？
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年8月15日 11:11
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [winterwindwang/Full-coverage-camouflage-adversarial-attack] 渲染过后的图片小于mask的大小 (Issue #33)
        
      
    
  


并且训练十个epoch的训练效果很不好，请问是否是这个原因影响，这个问题该怎么解决呢？使用的是您更改的neural_renderer

**Comment by zhoujiawei2** [comment]
使用generated_and_test.py

**Comment by zhoujiawei2** [comment]
在训练的过程中，也会出现这个问题，
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/21764def-1275-46d3-8c0b-a2796eb80618)

**Comment by winterwindwang** [comment]
我检查一下回复你
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年8月15日 11:16
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] 渲染过后的图片小于mask的大小 (Issue #33)
        
      
    
  

在训练的过程中，也会出现这个问题，

**Comment by zhoujiawei2** [comment]
感谢您的耐心回复，
原始：
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/3f17951a-7ce8-4d9e-89f8-c6361c93476b)

训练结果：
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/075213af-6576-457c-965b-a25b5d2a156d)


原始测试图像和训练后的图像车辆有一些差别，车标看起来不同，这个问题可能是车辆模型大小和数据集中使用的车辆模型不一样造成的吗？我使用的是car_assets中的3D模型信息，数据集使用的是https://drive.google.com/drive/folders/1vspvRxnZ3shOV4kM5ELcO9-xztapBThS。
同时这个问题似乎不只有我一个人发生，在https://github.com/idrl-lab/Full-coverage-camouflage-adversarial-attack/issues/9的提问中也有这种情况产生

**Comment by winterwindwang** [comment]
这个是正常的，带CARLA车标是因为数据采集自CARLA，但是渲染所使用的模型并不是CARLA里面的模型
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年8月15日 11:44
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] 渲染过后的图片小于mask的大小 (Issue #33)
        
      
    
  

感谢您的耐心回复，


原始测试图像和训练后的图像车辆有一些差别，车标看起来不同，这个问题可能是车辆模型大小和数据集中使用的车辆模型不一样造成的吗？我使用的是car_assets中的3D模型信息，数据集使用的是https://drive.google.com/drive/folders/1vspvRxnZ3shOV4kM5ELcO9-xztapBThS。
同时这个问题似乎不只有我一个人发生，在https://github.com/idrl-lab/Full-coverage-camouflage-adversarial-attack/issues/9的提问中也有这种情况产生

**Comment by zhoujiawei2** [comment]
您的意思是这种渲染过后的图像小于mask范围是正常现象吗？还是说车标不对应是正常的，而渲染过后的图像小于mask范围的问题仍然是需要解决的

**Comment by winterwindwang** [comment]
mask有部分对不齐是正常的，只要不是相差特别大就行。车标对不上也是正常的。&nbsp;


王冬华
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月15日(星期二) 中午1:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [winterwindwang/Full-coverage-camouflage-adversarial-attack] 渲染过后的图片小于mask的大小 (Issue #33)





 
您的意思是这种渲染过后的图像小于mask范围是正常现象吗？还是说车标不对应是正常的，而渲染过后的图像小于mask范围的问题仍然是需要解决的

**Comment by zhoujiawei2** [comment]
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/0be2e713-feee-4547-8de9-aaeb677d4b49)

![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/823033a1-1c47-414a-a14a-dcd608c4172b)

![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/544fabb6-2ee9-4a1f-9438-5f4e66ad9022)

![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/9383c48f-41cd-4489-99e3-f3da7a2c73fc)
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/bd396803-b5d7-4a2e-95f0-3e1dc33a1fe6)
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/6981dac3-2c6d-4884-88fa-3cd526a67cb7)
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/403e5692-9f2c-4f7b-a28f-9c107750ead4)
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/c4d27c54-4ad1-4c50-b9f2-89b7a996aa0c)
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/de23d2ff-66f7-4ba2-899c-dc1a790bdeea)
![image](https://github.com/winterwindwang/Full-coverage-camouflage-adversarial-attack/assets/95651451/f691b3ff-c8af-42a3-a34e-4f17cf6b22f3)



我放了12501到12510的测试样本生成图像，您看如果这个程度对不齐的程度是OK的吗？训练过程中每一张都与他们类似

**Comment by Francisapzii** [comment]
> ![image](https://private-user-images.githubusercontent.com/95651451/260617947-1995fd5f-bd22-4794-8625-4db3eeb1738a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NzIxNDEsIm5iZiI6MTcwNDg3MTg0MSwicGF0aCI6Ii85NTY1MTQ1MS8yNjA2MTc5NDctMTk5NWZkNWYtYmQyMi00Nzk0LTg2MjUtNGRiM2VlYjE3MzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDA3MzA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNjMyOGUwZDg3N2YzY2JiYjg5NWUxNTY5M2U3OTY0OWY0ZThiZGRlY2I4ZWQ2MGViOTU5OTc5N2IzZTk5M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Py_DBdyXTy5LRQ5HdhVi0NmTxjYgaEKhI5PSVFlRa9s) 并且训练十个epoch的训练效果很不好，请问是否是这个原因影响，这个问题该怎么解决呢？使用的是您更改的neural_rend

你好，能否帮忙看看，train_new中的数据是如何生成的？

**Comment by macalius** [comment]
@zhoujiawei2 冒昧的打扰了，我的纹理与您很相似，请问您复现出来论文中的纹理了吗
