### ISSUE TITLE
作者您好，我想问一下，您的训练最后的总损失大概在多少浮动

### ISSUE THREAD

**Issue by zhoujiawei2** [winterwindwang/Full-coverage-camouflage-adversarial-attack#34]
我按照您给的的参数进行试验，最终总损失一直保持在0.2左右，这是一个良好的损失值吗？但是在测试集上效果却不好，我不确定是测试的部分我出了问题，还是训练的过程中哪里出了问题

**Comment by qwc0121** [comment]
> 我按照您给的的参数进行试验，最终总损失一直保持在0.2左右，这是一个良好的损失值吗？但是在测试集上效果却不好，我不确定是测试的部分我出了问题，还是训练的过程中哪里出了问题

我也是，而且测试最终攻击效果，远低于原作者提供的纹理
