### ISSUE TITLE
DAS

### ISSUE THREAD

**Issue by zytxxn** [winterwindwang/Full-coverage-camouflage-adversarial-attack#5]
![image](https://user-images.githubusercontent.com/96740889/165204187-a5104e60-1de2-467f-a24a-96b0b60572a0.png)
DAS训练成功后得到loss和prob，但我不清楚的是用resnet152测试模型需要得到的acc是和prob一样吗？prob出来好像是每个数据预测的准确率，但文献里准确率acc是只有一个，请问这个acc该怎么计算？这个问题困扰我很久了！刚接触模型，看到您有跑过DAS，希望可以指导一下！十分感谢！

**Comment by winterwindwang** [comment]
这个loss只是记录训练时在训练集上的损失，你还要在测试集上重新计算。Acc的定义是分类正确的样本数占总样本数的比例。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "winterwindwang/Full-coverage-camouflage-adversarial-attack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 上午10:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[winterwindwang/Full-coverage-camouflage-adversarial-attack] DAS (Issue #5)





 

 DAS训练成功后得到loss和prob，但我不清楚的是用resnet152测试模型需要得到的acc是和prob一样吗？prob出来好像是每个数据预测的准确率，但文献里准确率acc是只有一个，请问这个acc该怎么计算？这个问题困扰我很久了！刚接触模型，看到您有跑过DAS，希望可以指导一下！十分感谢！

**Comment by zytxxn** [comment]
那请问prob是每个数据预测的准确率吗？Acc的具体计算和prob有关系吗？
