### ISSUE TITLE
KeyError: 'msgs'

### ISSUE THREAD

**Issue by logicsh** [winterwindwang/Full-coverage-camouflage-adversarial-attack#7]
File "/root/Full-coverage-camouflage-adversarial-attack-gh-pages/src/utils/datasets_fca.py", line 188, in <listcomp>
    [cache.pop(k) for k in ('hash', 'version', 'msgs')]  # remove items 
KeyError: 'msgs'

**Comment by winterwindwang** [comment]
remove the `msgs` parameter

**Comment by logicsh** [comment]
thanks!还有一个问题就是  File "/root/Full-coverage-camouflage-adversarial-attack-gh-pages/src/utils/datasets_fca.py", line 424, in load_image
    data = np.load(path, allow_pickle=True)  # .item() # .item()      #
  File "/root/anaconda3/envs/fca/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/phy_attack/train/data10067.npz'
很奇怪我明明指定的npz路径（das的）有这个文件来着
